//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pomodoro
{
    using System;
    using System.Collections.Generic;
    
    public partial class pomodoro
    {
        public int id { get; set; }
        public System.DateTime date { get; set; }
        public int tags_id { get; set; }
    
        public virtual tags tags { get; set; }
    }
}
